-- Create jobs table
CREATE TABLE IF NOT EXISTS jobs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL,
    company_logo VARCHAR(500),
    industry VARCHAR(100) NOT NULL,
    location VARCHAR(255) NOT NULL,
    country VARCHAR(100) NOT NULL,
    salary_min DECIMAL(10,2),
    salary_max DECIMAL(10,2),
    currency VARCHAR(3) DEFAULT 'USD',
    job_type ENUM('full-time', 'part-time', 'contract', 'internship') NOT NULL,
    experience_level ENUM('entry', 'junior', 'mid', 'senior', 'executive') NOT NULL,
    work_type ENUM('remote', 'hybrid', 'on-site') NOT NULL,
    description TEXT NOT NULL,
    requirements JSON,
    benefits JSON,
    skills JSON,
    posted_by ENUM('platform', 'company', 'individual') NOT NULL,
    external_url VARCHAR(500),
    contact_email VARCHAR(255),
    is_urgent BOOLEAN DEFAULT FALSE,
    is_featured BOOLEAN DEFAULT FALSE,
    status ENUM('active', 'paused', 'closed', 'expired') DEFAULT 'active',
    application_deadline DATE,
    views_count INT DEFAULT 0,
    applications_count INT DEFAULT 0,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_company (company),
    INDEX idx_location (location),
    INDEX idx_job_type (job_type),
    INDEX idx_experience (experience_level),
    INDEX idx_status (status),
    INDEX idx_posted_by (posted_by),
    INDEX idx_created_at (created_at)
);
