-- Create tenders table
CREATE TABLE IF NOT EXISTS tenders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    organization VARCHAR(255) NOT NULL,
    organization_logo VARCHAR(500),
    sector ENUM('government', 'healthcare', 'transportation', 'private', 'manufacturing', 'education', 'other') NOT NULL,
    category VARCHAR(100) NOT NULL,
    contract_value_min DECIMAL(15,2),
    contract_value_max DECIMAL(15,2),
    currency VARCHAR(3) DEFAULT 'USD',
    duration VARCHAR(100),
    location VARCHAR(255) NOT NULL,
    country VARCHAR(100) NOT NULL,
    deadline DATE NOT NULL,
    description TEXT NOT NULL,
    detailed_description TEXT,
    requirements JSON,
    documents JSON,
    project_scope JSON,
    technical_requirements JSON,
    organization_info JSON,
    submission_process JSON,
    evaluation_criteria JSON,
    submission_type ENUM('online-portal', 'electronic', 'sealed-bid', 'proposal', 'technical') NOT NULL,
    is_urgent BOOLEAN DEFAULT FALSE,
    bond_required BOOLEAN DEFAULT FALSE,
    prequalification_required BOOLEAN DEFAULT FALSE,
    status ENUM('active', 'closed', 'awarded', 'cancelled') DEFAULT 'active',
    views_count INT DEFAULT 0,
    submissions_count INT DEFAULT 0,
    external_url VARCHAR(500),
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_organization (organization),
    INDEX idx_sector (sector),
    INDEX idx_location (location),
    INDEX idx_deadline (deadline),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
);
