-- Create opportunities table
CREATE TABLE IF NOT EXISTS opportunities (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    organization VARCHAR(255) NOT NULL,
    organization_logo VARCHAR(500),
    type ENUM('scholarship', 'fellowship', 'grant', 'program', 'internship', 'competition', 'volunteer') NOT NULL,
    category VARCHAR(100) NOT NULL,
    amount_min DECIMAL(15,2),
    amount_max DECIMAL(15,2),
    currency VARCHAR(3) DEFAULT 'USD',
    duration VARCHAR(100),
    location VARCHAR(255),
    country VARCHAR(100),
    deadline DATE,
    description TEXT NOT NULL,
    detailed_description TEXT,
    eligibility_criteria JSON,
    application_process JSON,
    benefits JSON,
    requirements JSON,
    documents JSON,
    is_urgent BOOLEAN DEFAULT FALSE,
    is_featured BOOLEAN DEFAULT FALSE,
    status ENUM('active', 'closed', 'completed') DEFAULT 'active',
    views_count INT DEFAULT 0,
    applications_count INT DEFAULT 0,
    external_url VARCHAR(500),
    contact_email VARCHAR(255),
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_organization (organization),
    INDEX idx_type (type),
    INDEX idx_location (location),
    INDEX idx_deadline (deadline),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
);
