-- Create courses table
CREATE TABLE IF NOT EXISTS courses (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    detailed_description TEXT,
    instructor VARCHAR(255) NOT NULL,
    instructor_bio TEXT,
    category VARCHAR(100) NOT NULL,
    subcategory VARCHAR(100),
    level ENUM('beginner', 'intermediate', 'advanced') NOT NULL,
    duration_hours INT,
    price DECIMAL(10,2),
    currency VARCHAR(3) DEFAULT 'USD',
    thumbnail_url VARCHAR(500),
    video_url VARCHAR(500),
    materials JSON,
    learning_objectives JSON,
    prerequisites JSON,
    curriculum JSON,
    is_free BOOLEAN DEFAULT FALSE,
    is_featured BOOLEAN DEFAULT FALSE,
    status ENUM('draft', 'published', 'archived') DEFAULT 'draft',
    enrollment_count INT DEFAULT 0,
    rating DECIMAL(3,2),
    review_count INT DEFAULT 0,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_category (category),
    INDEX idx_level (level),
    INDEX idx_status (status),
    INDEX idx_is_free (is_free),
    INDEX idx_created_at (created_at)
);
